---
abstract: 'forking prove'
author:
  - 'Tatsuhiko Miyagawa <miyagawa@bulknews.net>'
build_requires:
  ExtUtils::MakeMaker: '0'
  Test::More: '0.94'
  Test::Requires: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.142060'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: forkprove
no_index:
  directory:
    - t
    - inc
requires:
  App::Prove: '3.25'
  TAP::Harness: '3.25'
  parent: '0.221'
  version: '0.77'
version: v0.4.11
