---
abstract: ~
author:
  - 'Tatsuhiko Miyagawa <miyagawa@bulknews.net>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0.88
  Test::Requires: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: forkprove
no_index:
  directory:
    - inc
    - t
    - xt
provides:
  App::ForkProve:
    file: lib/App/ForkProve.pm
    version: v0.1.3
  App::ForkProve::SourceHandler:
    file: lib/App/ForkProve/SourceHandler.pm
requires:
  App::Prove: 3.25
  TAP::Harness: 3.25
  parent: 0.221
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/miyagawa/forkprove.git
version: 0.1.3
