---
abstract: 'forking prove'
author:
  - 'Tatsuhiko Miyagawa <miyagawa@bulknews.net>'
build_requires:
  Module::Build: 0.3601
  Test::More: 0.88
  Test::Requires: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.0, Dist::Zilla version 4.300033, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: forkprove
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  App::Prove: 3.25
  TAP::Harness: 3.25
  parent: 0.221
  perl: 5.008001
  version: 0.77
resources:
  bugtracker: https://github.com/miyagawa/forkprove/issues
  homepage: https://github.com/miyagawa/forkprove
  repository: https://github.com/miyagawa/forkprove.git
version: v0.4.7
x_contributors:
  - 'Jesse Luehrs <doy@tozt.net>'
  - 'Jonathan Swartz <swartz@pobox.com>'
  - 'Shigeki Morimoto <github@morimo.to>'
